pipeline {
    agent {
        docker {
            image 'cypress/browsers:node-20.16.0-chrome-124.0.6367.91-1-ff-126.0.1-1'
            args '-e DISPLAY=:99'
        }
    }

    stages {
        stage('Install dependencies') {
            steps {
                sh 'npm ci || npm install'
            }
        }

        stage('Run Cypress tests') {
            steps {
                sh '''
                    Xvfb :99 -screen 0 1280x720x24 &
                    sleep 3
                    npx cypress run --record --key 75c95202-b753-415a-82eb-9d67e942795a --env allure=true,allureResultsPath=cypress/results
                '''
            }
        }

        stage('Allure report') {
            steps {
                sh 'npx allure generate cypress/results --clean -o cypress/report'
                archiveArtifacts artifacts: 'cypress/report/**', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'cypress/videos/**, cypress/screenshots/**', allowEmptyArchive: true
            
            allure([
                results: [[path: 'cypress/results']],
                reportBuildPolicy: 'ALWAYS'
            ])
        }
    }
}
